apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jmdh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-jmdh@sha256:dcf7cec956d5029e82473615890bc11d1e262edee4eadbf164ef159c121d08c1
        name: my-nodejs
        resources: {}
status: {}
